# Generated by Django 3.1.7 on 2021-12-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211216_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('DR', 'Draft'), ('PU', 'Publish'), ('PR', 'Private')], default='DR', max_length=2),
        ),
    ]
