# Generated by Django 3.1.7 on 2021-12-21 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_publish_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
